language: python
python:
  - "3.7"  
  - "3.8"
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - cd tests
  - pytest test_main.py
  
